### ISSUE TITLE
Umbraco.AuditLogViewer Not working with Umbraco v11

### ISSUE THREAD

**Issue by gurumurthyjv** [DanDiplo/Umbraco.AuditLogViewer#13]
Hi,

I have installed Umbraco.AuditLogViewer **v10.0.1** into Umbraco **v11.4.2** and it loads and works fine in my local, but the same is not loading on Azure app service after deployment.

When ever I click on this under setting get below error on console and screen remains blank also I see that the reference JS files are not being downloaded on console source tab, below are the reference images.

**On Azure App**
![image](https://github.com/DanDiplo/Umbraco.AuditLogViewer/assets/36879551/87972cc1-e10c-4ca3-af15-3711876e94b0)

**On My Local**
![image](https://github.com/DanDiplo/Umbraco.AuditLogViewer/assets/36879551/99ce69a0-ed0a-42a6-a9a2-eadb0f4ecd43)

Looking for your suggestions and help here, or still is package is not supported with Umbraco v11.

Thanks,
Gurumurthy JV

**Comment by DanDiplo** [comment]
Hi @gurumurthyjv Sorry for delay, I've been away.

I'm not that familiar with Azure Web Apps, as I don't personally use them, but there should be no reason it wouldn't work. I guess it probably depends on your deploy process? Did you deploy the JS files to the Azure app? Normally, Nuget restore would do this, but you could always deploy them manually or via your CI/CD process.

Could you just try copying them to the app?

**Comment by gurumurthyjv** [comment]
Hi @DanDiplo ,

Thanks for your reply, I have deployed all JS files manually and tried but still not working.

So, Uninstalled the package and reinstalled again and made some config changes for "RuntimeMinification" and deployed to Azure and it started working now, So every time when we rebuild the solution, the DiploAuditLogViewer folder under App_Plugins will be deleted and recreated as part of nuget restore.

Any how now its loading, we can close this issue.

Thanks again for your inputs.

Thanks,
Gurumurthy JV

**Comment by DanDiplo** [comment]
Glad to hear it and thanks for updating me!
