### ISSUE TITLE
Umbraco 8 support

### ISSUE THREAD

**Issue by vonbarnekowa** [DanDiplo/Umbraco.AuditLogViewer#3]
Hey,

Is support for Umbraco 8 planned?

Best,
Alec

**Comment by DanDiplo** [comment]
Hi. At some point, it probably will. But I've yet to really explore the new APIs etc so it will require a major rewrite. So I've no short-term plans yet, but eventually I expect to port it.

**Comment by DanDiplo** [comment]
@vonbarnekowa The time has arrived! I've released it for v8 now (with some new features!). Read more:

https://www.diplo.co.uk/blog/web-development/diplo-audit-log-viewer-for-umbraco-8/
